export const translations = {
  es: {
    'meta.title': 'Agustín — Desarrollador de software', 'meta.description': 'Portfolio de Agustín, desarrollador de software orientado a crear productos digitales claros, funcionales y bien ejecutados.',
    'controls.language': 'Cambiar idioma', 'controls.theme.light': 'Activar modo claro', 'controls.theme.dark': 'Activar modo oscuro', 'nav.available': 'disponible',
    'nav.projects': 'Proyectos', 'nav.about': 'Sobre mí', 'nav.technologies': 'Tecnologías', 'nav.process': 'Cómo trabajo', 'nav.contact': 'Contacto', 'nav.label': 'Navegación principal', 'nav.open': 'Abrir menú', 'nav.close': 'Cerrar menú', 'nav.home': 'Agustín, ir al inicio', 'nav.status': 'Estado del sitio',
    'hero.role': 'Desarrollador de software y web', 'hero.flow': 'imaginar / planificar / crear', 'hero.hello': 'Soy Agustín.', 'hero.line1': 'De tener una', 'hero.idea': ' gran idea', 'hero.line2': 'a', 'hero.line3': 'hacerla realidad.', 'hero.description': 'No hace falta tener cada detalle resuelto para empezar. Me gusta entender qué quieres conseguir, encontrar la mejor forma de hacerlo posible y construirlo con creatividad, pasión y atención al detalle.', 'hero.projects': 'Ver proyectos', 'hero.contact': 'Contactar', 'hero.runtime': 'webs a medida', 'hero.ai': 'aplicaciones interactivas', 'hero.web': 'desarrollo sólido', 'hero.scroll': 'desplazar',
    'editor.files': 'Archivos del editor', 'editor.status': 'Estado del editor', 'editor.capture': 'Captura real pendiente', 'editor.role': 'Desarrollador de software', 'editor.web': 'Desarrollo web', 'editor.gaming': 'Videojuegos', 'editor.technology': 'Tecnología', 'editor.current': 'Construyendo cosas nuevas', 'editor.line': 'Lín', 'editor.column': 'Col', 'editor.nowTitle': 'En este momento', 'editor.now1': 'Trabajando en nuevos proyectos digitales,', 'editor.now2': 'probando nuevas herramientas y', 'editor.now3': 'aprendiendo sobre la marcha.', 'editor.nowComment': 'una mejora más y lo termino...',
    'workflow.label': 'Flujo de trabajo', 'workflow.ready': 'listo', 'workflow.understand': 'Entender', 'workflow.context': 'visión + contexto', 'workflow.build': 'Construir', 'workflow.code': 'código + creatividad', 'workflow.refine': 'Refinar', 'workflow.detail': 'criterio + detalle', 'workflow.deliver': 'Entregar', 'workflow.product': 'producto web', 'workflow.input': 'entrada', 'workflow.active': 'activo', 'workflow.review': 'revisión', 'workflow.tools': 'stack',
    'projects.bridge': 'idea → flujo → producto', 'projects.navigation': 'Navegación entre proyectos',
    'projects.label': 'Productos reales', 'projects.title1': 'Explora el', 'projects.title2': 'trabajo.', 'projects.intro': 'Dos proyectos, presentados sin métricas ni detalles inventados.', 'projects.select': 'Seleccionar proyecto', 'projects.info': 'Información de', 'projects.preview': 'Vista previa', 'projects.overview': 'Resumen', 'projects.stack': 'Tecnologías', 'projects.confirmed': 'Tecnologías confirmadas', 'projects.stackPending': 'El stack se incorporará cuando la información esté confirmada.', 'projects.context': 'Contexto del producto', 'projects.contribution': 'Participación', 'projects.open': 'Abrir producto', 'projects.linkPending': 'Enlace pendiente de confirmar', 'projects.previous': 'Proyecto anterior', 'projects.next': 'Proyecto siguiente', 'projects.capture': 'Captura real pendiente', 'projects.captureSpace': 'Espacio preparado para una captura real de',
    'project.rift.eyebrow': 'Producto web · Wild Rift', 'project.rift.description': 'Una aplicación web relacionada con League of Legends: Wild Rift, pensada para convertir información del juego en una experiencia clara y útil.', 'project.rift.contribution': 'Proyecto de desarrollo web.', 'project.myfinteem.eyebrow': 'Proyecto de software', 'project.myfinteem.description': 'Un proyecto colaborativo cuya historia, alcance y contribución se documentarán aquí con detalle.', 'project.myfinteem.contribution': 'Participación pendiente de completar.',
    'about.label': 'Cómo pienso', 'about.title1': 'Resolver antes', 'about.title2': 'que decorar.', 'about.intro': 'Mi forma de trabajar conecta intención, criterio y ejecución. El código es una herramienta dentro de un proceso más amplio.', 'about.understand': 'Comprender', 'about.understandText': 'Antes de elegir herramientas, busco entender el problema y qué necesita conseguir el producto.', 'about.define': 'Definir', 'about.defineText': 'Ordeno la información y traduzco la intención en una dirección clara y construible.', 'about.build': 'Construir', 'about.buildText': 'Combino desarrollo, herramientas modernas e IA asistida según lo que el proyecto necesita.', 'about.refine': 'Refinar', 'about.refineText': 'Reviso la experiencia, ajusto detalles y convierto la primera solución en un resultado más sólido.',
    'tech.label': 'Arsenal adaptable', 'tech.title1': 'Herramientas que', 'tech.title2': 'trabajan juntas.', 'tech.select': 'Seleccionar tecnología', 'tech.inspector': 'inspector', 'tech.related': 'Se relaciona con', 'tech.independent': 'Herramienta independiente en este mapa', 'tech.language': 'Lenguaje', 'tech.frontend': 'Frontend', 'tech.data': 'Datos', 'tech.backend': 'Backend y datos', 'tech.services': 'Servicios', 'tech.tool': 'Herramienta', 'tech.deploy': 'Despliegue', 'tech.ai': 'IA asistida',
    'tech.javascript': 'Base para construir experiencias web interactivas.', 'tech.typescript': 'Añade tipos y claridad a aplicaciones JavaScript.', 'tech.react': 'Permite construir interfaces mediante componentes y estados.', 'tech.next': 'Framework de React para aplicaciones web y renderizado flexible.', 'tech.vite': 'Entorno rápido para desarrollar y compilar aplicaciones frontend.', 'tech.python': 'Lenguaje multipropósito para lógica, automatización y servicios.', 'tech.cpp': 'Lenguajes para comprender y trabajar cerca del sistema.', 'tech.sql': 'Lenguaje para consultar y organizar datos relacionales.', 'tech.supabase': 'Servicios backend sobre PostgreSQL, incluyendo base de datos y autenticación cuando se requieren.', 'tech.rest': 'Comunicación estructurada entre una interfaz y servicios externos.', 'tech.git': 'Control de versiones para trabajar de forma trazable e iterativa.', 'tech.github': 'Alojamiento de código y colaboración alrededor de repositorios.', 'tech.vercel': 'Despliegue web conectado al flujo de desarrollo.', 'tech.codex': 'Asistencia para explorar, implementar y revisar trabajo de desarrollo.',
    'work.label': 'De la idea al producto', 'work.title1': 'No todas las webs', 'work.title2': 'necesitan lo mismo.', 'work.intro': 'Primero entiendo qué quieres lograr. Después elijo cómo construirlo.', 'work.question': '¿Cuál es el objetivo?', 'work.clients': 'Conseguir clientes', 'work.clientsNote': 'Priorizar confianza y contacto', 'work.portfolio': 'Mostrar proyectos', 'work.portfolioNote': 'Priorizar trabajo y criterio', 'work.shop': 'Vender productos', 'work.shopNote': 'Priorizar catálogo y compra', 'work.preview': 'Vista conceptual', 'work.example': 'Ejemplo ilustrativo', 'work.clientsTag': 'ESTRATEGIA DIGITAL', 'work.clientsTitle': 'Tu próxima etapa empieza clara.', 'work.clientsText': 'Convertimos desafíos en decisiones concretas.', 'work.talk': 'Hablemos →', 'work.services': 'Servicios   Equipo', 'work.selected': 'TRABAJO SELECCIONADO / 2026', 'work.visible': 'Ideas hechas visibles.', 'work.bag': 'Cesta (0)', 'work.new': 'Nuevo', 'work.object': 'Objeto / 01', 'work.everyday': 'Diseño cotidiano.', 'work.add': 'Añadir · €00',
    'contact.label': 'Hablemos', 'contact.kicker': '¿Tienes una idea, un proyecto o una oportunidad?', 'contact.title1': 'Cuéntame qué', 'contact.title2': 'quieres construir.', 'contact.note': 'Responde cuatro campos. El resto lo conversamos.', 'contact.name': 'Nombre', 'contact.namePlaceholder': 'Tu nombre', 'contact.email': 'Correo electrónico', 'contact.emailPlaceholder': 'nombre@correo.com', 'contact.type': 'Tipo de consulta', 'contact.select': 'Selecciona una opción', 'contact.web': 'Quiero desarrollar una web', 'contact.app': 'Tengo una idea para una aplicación', 'contact.improve': 'Quiero mejorar un proyecto existente', 'contact.job': 'Oportunidad laboral', 'contact.other': 'Otra consulta', 'contact.project': 'Proyecto o necesidad', 'contact.projectPlaceholder': 'Objetivo, contexto y qué necesitas resolver…', 'contact.characters': 'caracteres', 'contact.privacy': 'Estos datos se usarán únicamente para responder tu consulta. Revisión legal definitiva pendiente antes de la publicación.', 'contact.send': 'Enviar consulta', 'contact.sending': 'Enviando…', 'contact.success': 'Consulta enviada correctamente. Gracias por escribir.', 'contact.unavailable': 'El envío todavía no está configurado. Puedes usar el correo de contacto cuando esté disponible.', 'contact.failed': 'No se pudo enviar la consulta. Inténtalo de nuevo más tarde.', 'contact.nameError': 'Introduce un nombre válido.', 'contact.emailError': 'Introduce un correo válido.', 'contact.typeError': 'Selecciona un tipo de consulta.', 'contact.messageError': 'Cuéntame un poco más (mínimo 20 caracteres).', 'contact.githubPending': 'GitHub · pendiente', 'contact.linkedinPending': 'LinkedIn · pendiente', 'contact.resume': 'CV · próximamente', 'contact.top': 'Volver arriba ↑',
  },
  en: {
    'meta.title': 'Agustín — Software Developer', 'meta.description': 'Agustín’s portfolio — a product-minded software developer building clear, functional, thoughtfully executed digital experiences.',
    'controls.language': 'Change language', 'controls.theme.light': 'Switch to light mode', 'controls.theme.dark': 'Switch to dark mode', 'nav.available': 'available',
    'nav.projects': 'Projects', 'nav.about': 'About', 'nav.technologies': 'Technologies', 'nav.process': 'How I work', 'nav.contact': 'Contact', 'nav.label': 'Main navigation', 'nav.open': 'Open menu', 'nav.close': 'Close menu', 'nav.home': 'Agustín, back to top', 'nav.status': 'Site status',
    'hero.role': 'Software & web developer', 'hero.flow': 'imagine / plan / create', 'hero.hello': 'I’m Agustín.', 'hero.line1': 'From having a', 'hero.idea': ' great idea', 'hero.line2': 'to bringing it', 'hero.line3': 'to life.', 'hero.description': "You don't need to have every detail figured out to get started. I enjoy understanding what you want to achieve, finding the best way to make it happen, and bringing it to life with creativity, passion, and attention to detail.", 'hero.projects': 'View projects', 'hero.contact': 'Get in touch', 'hero.runtime': 'custom websites', 'hero.ai': 'interactive apps', 'hero.web': 'solid development', 'hero.scroll': 'scroll',
    'editor.files': 'Editor files', 'editor.status': 'Editor status', 'editor.capture': 'Real screenshot pending', 'editor.role': 'Software Developer', 'editor.web': 'Web Development', 'editor.gaming': 'Gaming', 'editor.technology': 'Technology', 'editor.current': 'Building new things', 'editor.line': 'Ln', 'editor.column': 'Col', 'editor.nowTitle': 'Right now', 'editor.now1': 'Working on new digital projects,', 'editor.now2': 'exploring new tools and', 'editor.now3': 'learning as I go.', 'editor.nowComment': 'just one more tweak and I’m done...',
    'workflow.label': 'Work process', 'workflow.ready': 'ready', 'workflow.understand': 'Understand', 'workflow.context': 'vision + context', 'workflow.build': 'Build', 'workflow.code': 'code + creativity', 'workflow.refine': 'Refine', 'workflow.detail': 'judgment + detail', 'workflow.deliver': 'Deliver', 'workflow.product': 'web product', 'workflow.input': 'input', 'workflow.active': 'active', 'workflow.review': 'review', 'workflow.tools': 'stack',
    'projects.bridge': 'idea → workflow → product', 'projects.navigation': 'Project navigation',
    'projects.label': 'Real products', 'projects.title1': 'Explore the', 'projects.title2': 'work.', 'projects.intro': 'Two projects, presented without invented metrics or details.', 'projects.select': 'Select a project', 'projects.info': 'Information about', 'projects.preview': 'Preview', 'projects.overview': 'Overview', 'projects.stack': 'Stack', 'projects.confirmed': 'Confirmed technologies', 'projects.stackPending': 'The stack will be added once the information is confirmed.', 'projects.context': 'Product context', 'projects.contribution': 'Contribution', 'projects.open': 'Open product', 'projects.linkPending': 'Link pending confirmation', 'projects.previous': 'Previous project', 'projects.next': 'Next project', 'projects.capture': 'Real screenshot pending', 'projects.captureSpace': 'Space reserved for a real screenshot of',
    'project.rift.eyebrow': 'Web product · Wild Rift', 'project.rift.description': 'A web application related to League of Legends: Wild Rift, designed to turn game information into a clear and useful experience.', 'project.rift.contribution': 'Web development project.', 'project.myfinteem.eyebrow': 'Software project', 'project.myfinteem.description': 'A collaborative project whose story, scope, and contribution will be documented here in detail.', 'project.myfinteem.contribution': 'Contribution details pending.',
    'about.label': 'How I think', 'about.title1': 'Solve before', 'about.title2': 'decorating.', 'about.intro': 'My process connects intent, judgment, and execution. Code is one tool within a broader way of working.', 'about.understand': 'Understand', 'about.understandText': 'Before choosing tools, I focus on the problem and what the product needs to achieve.', 'about.define': 'Define', 'about.defineText': 'I organize the information and translate intent into a clear, buildable direction.', 'about.build': 'Build', 'about.buildText': 'I combine development, modern tools, and AI assistance according to the project’s needs.', 'about.refine': 'Refine', 'about.refineText': 'I review the experience, adjust the details, and turn the first solution into a stronger result.',
    'tech.label': 'Adaptive toolkit', 'tech.title1': 'Tools that', 'tech.title2': 'work together.', 'tech.select': 'Select a technology', 'tech.inspector': 'inspector', 'tech.related': 'Works with', 'tech.independent': 'Independent tool in this map', 'tech.language': 'Language', 'tech.frontend': 'Frontend', 'tech.data': 'Data', 'tech.backend': 'Backend & data', 'tech.services': 'Services', 'tech.tool': 'Tool', 'tech.deploy': 'Deployment', 'tech.ai': 'AI-assisted',
    'tech.javascript': 'The foundation for building interactive web experiences.', 'tech.typescript': 'Adds types and clarity to JavaScript applications.', 'tech.react': 'Builds interfaces through components and state.', 'tech.next': 'A React framework for web applications and flexible rendering.', 'tech.vite': 'A fast environment for developing and building frontend applications.', 'tech.python': 'A general-purpose language for logic, automation, and services.', 'tech.cpp': 'Languages for understanding and working closer to the system.', 'tech.sql': 'A language for querying and organizing relational data.', 'tech.supabase': 'PostgreSQL-based backend services, including database and authentication when needed.', 'tech.rest': 'Structured communication between an interface and external services.', 'tech.git': 'Version control for traceable, iterative work.', 'tech.github': 'Code hosting and collaboration around repositories.', 'tech.vercel': 'Web deployment connected to the development workflow.', 'tech.codex': 'Assistance for exploring, implementing, and reviewing development work.',
    'work.label': 'From idea to product', 'work.title1': 'Not every website', 'work.title2': 'needs the same thing.', 'work.intro': 'First I understand what you want to achieve. Then I decide how to build it.', 'work.question': 'What is the goal?', 'work.clients': 'Win new clients', 'work.clientsNote': 'Prioritize trust and contact', 'work.portfolio': 'Showcase work', 'work.portfolioNote': 'Prioritize projects and perspective', 'work.shop': 'Sell products', 'work.shopNote': 'Prioritize catalog and purchase', 'work.preview': 'Concept preview', 'work.example': 'Illustrative example', 'work.clientsTag': 'DIGITAL STRATEGY', 'work.clientsTitle': 'Your next stage starts with clarity.', 'work.clientsText': 'We turn challenges into clear decisions.', 'work.talk': 'Let’s talk →', 'work.services': 'Services   Team', 'work.selected': 'SELECTED WORK / 2026', 'work.visible': 'Ideas made visible.', 'work.bag': 'Bag (0)', 'work.new': 'New', 'work.object': 'Object / 01', 'work.everyday': 'Everyday design.', 'work.add': 'Add · €00',
    'contact.label': 'Let’s talk', 'contact.kicker': 'Have an idea, a project, or an opportunity?', 'contact.title1': 'Tell me what', 'contact.title2': 'you want to build.', 'contact.note': 'Four fields are enough to start. We can discuss the rest.', 'contact.name': 'Name', 'contact.namePlaceholder': 'Your name', 'contact.email': 'Email address', 'contact.emailPlaceholder': 'name@email.com', 'contact.type': 'Type of inquiry', 'contact.select': 'Select an option', 'contact.web': 'I want to build a website', 'contact.app': 'I have an application idea', 'contact.improve': 'I want to improve an existing project', 'contact.job': 'Job opportunity', 'contact.other': 'Another inquiry', 'contact.project': 'Project or need', 'contact.projectPlaceholder': 'Goal, context, and what you need to solve…', 'contact.characters': 'characters', 'contact.privacy': 'This information will only be used to reply to your inquiry. Final legal review pending before publication.', 'contact.send': 'Send inquiry', 'contact.sending': 'Sending…', 'contact.success': 'Your inquiry was sent successfully. Thanks for reaching out.', 'contact.unavailable': 'Form delivery is not configured yet. You can use the contact email once it is available.', 'contact.failed': 'The inquiry could not be sent. Please try again later.', 'contact.nameError': 'Enter a valid name.', 'contact.emailError': 'Enter a valid email address.', 'contact.typeError': 'Select an inquiry type.', 'contact.messageError': 'Please share a little more (at least 20 characters).', 'contact.githubPending': 'GitHub · pending', 'contact.linkedinPending': 'LinkedIn · pending', 'contact.resume': 'Résumé · coming soon', 'contact.top': 'Back to top ↑',
  },
} as const

export type Language = keyof typeof translations
export type TranslationKey = keyof typeof translations.es
